### ISSUE TITLE
Adding library as dependency

### ISSUE THREAD

**Issue by barisAtmn** [carpe/scalambda#46]
How can I add library dependencies to sbt file ? 
I want to add zio library, however I get `not found: object zio` error. Besides I tried to add another libraries and got errors.

`lazy val greeter = (project in file("."))
  .enablePlugins(ScalambdaPlugin)
  .settings(
    //ZIO
    libraryDependencies += "dev.zio" %% "zio" % "1.0.1",
    // this call enables Scalambda, and sets the class found at this path to be the handler
    scalambda("my.companyname.greeter.Greeter")
)
`

**Comment by rui-ribeiro** [comment]
Hello @barisAtmn,

Can you please provide some more information? Like which version you scalambda are you using?

```scala 
lazy val example = project
  .enablePlugins(ScalambdaPlugin)
  .settings(
    scalambda(
      functionClasspath = ??? // example: "io.carpe.example.ExampleFunction
    )
  )
  .settings(
    libraryDependencies += "dev.zio" %% "zio" % "1.0.1",
  )

```

I believe the example above should work, please let me know if it does.

**Comment by barisAtmn** [comment]
I use 6.0.0. 
addSbtPlugin("io.carpe" % "sbt-scalambda" % "6.0.0")

It may be my bad.
I updated functionClassPath' name in scalambda function in sbt file. It was giving error in aws that lambda function is not found. That is why I changed functionClassPath with ```package name + className```.

package name : my.companyname.greeter
class name: Greeter

I changed it to first version from Giter8 template and it worked. ```scalambda("my.companyname.Greeter")```

```
lazy val greeter = (project in file("."))
  .enablePlugins(ScalambdaPlugin)
  .settings(
    // this call enables Scalambda, and sets the class found at this path to be the handler
    scalambda("my.companyname.Greeter")
   ).settings(
    libraryDependencies += "dev.zio" %% "zio" % "1.0.1"
  )

```

**Comment by SwiftEngineer** [comment]
Hey @barisAtmn! In case you haven't already found your solution yet, I think your issue might be with ZIO, rather than Scalambda. Looks like you might be mixing up `zio.IO` with `zio.ZIO`? I'm not sure the latter exists in the ZIO library.

Just a head's up: Considering how you are using ZIO instead of cats, you might also need this library as well (if you want to use the `ScalambdaIO` abstract class): https://github.com/zio/interop-cats

Best of luck!

**Comment by barisAtmn** [comment]
Hey @SwiftEngineer 

Thank you for response. 
I started to using sbt 1.4.1 and now it works. We can close it. 

Thank you!
